# Problem Set 2 CS174
---
The following problem set will focus on the lessons on Numpy and advanced Python functions. Answer the following guide questions by writing functions or code in cells that accomplish the requirements.

1. Create a function that takes in 3 parameters (integer n, integer a, integer b), and generates an nxn numpy matrix with random values from the range a to b inclusive. **2 pts.**

2. Present a count plot of the top 20 occurring words in **data/networks.txt**. Use the stopword file **data/stop.txt** to filter out the stopwords **2 pts.**

3. Using **data/ateneo.txt** and **data/tl-en.txt**, convert the phrases into straight english phrases. Leave words with no translation be. **6 pts.**

4. Using **data/tl-en.txt**, create a one-to-one English to Filipino translation of your favorite English song. Develop functions to handle pluralities, and multiple entry results. Discuss your code and please put at least 1-liner docs for the functions. **10 pts.**
       
### Bonus:
Repeat #4 but do a Filipino to English translation of your favorite Filipno song. Same specs apply. **5 pts.**

Deadline **Feb 20 11:59PM**. Submission link to be posted in Moodle. 
Submit the .ipynb file only with name <SURNAME>_<ID NUMBER>.ipynb. 
    
Sample: **"BAUTISTA_110464.ipynb"**

In [5]:
# libraries needed
import numpy as np

#1

In [17]:
def generateRandMatrix(n, a, b):
    if a > b or n < 1 or not isinstance(n, int): return None 
    return np.random.randint(low=a, high=b+1, size=(n,n))

print(generateRandMatrix(5,1,5))

[[4 3 2 4 5]
 [2 3 3 2 3]
 [4 4 2 3 2]
 [2 2 3 3 2]
 [5 5 4 4 1]]


#2

In [31]:
#load networks.txt
with open('./data/networks.txt', 'r') as f1:
    network = f1.read()
    txtList = network.replace(".", "").split(" ")
#make word count dict of networks.txt
    txtWordCount = {}
    for txt in txtList:
        if txt not in txtWordCount.keys():
            txtWordCount[txt] = 1
        else:
            txtWordCount[txt] += 1

#order dict by value
    txtWordCount = {k: v for k, v in sorted(txtWordCount.items(), key=lambda item: item[1], reverse=True)}
    print(txtWordCount)

#load stop.txt
    with open('./data/stop.txt', 'r') as f2:
#append top 20 to new dict while checking if it's in stop.txt
        

NameError: name 'f2' is not defined